#!/bin/bash

#!/bin/bash

COUNT=${1-1}

docker build -t jmeter-base jmeter-base
docker-compose build
docker-compose up -d
docker-compose scale master=1 slave=$COUNT

SLAVE_IP=$(docker inspect -f '{{.Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) | grep slave | awk -F' ' '{print $2}' | tr '\n' ',' | sed 's/.$//')
WDIR=`docker exec -it master /bin/pwd | tr -d '\r'`
mkdir -p results

echo $WDIR


for filename in scripts/*.jmx; do
    NAME=$(basename $filename)
    NAME="${NAME%.*}"
    eval "docker cp $filename master:$WDIR/scripts/"
    eval "docker cp /home/madhu/users.csv master:$WDIR"
    eval "docker exec -it master /bin/bash -c 'mkdir $NAME && cd $NAME && ../bin/jmeter -n -t  ../$filename -l output.csv -e -o web -R$SLAVE_IP'"
    eval "docker cp master:$WDIR/$NAME results/"
done


#To stop docker and docker compose and remove all
# docker-compose stop && docker-compose rm -f
#To stop all containers are running
 # docker stop $(docker ps -a -q)
#TO remove all containers
   # docker rm $(docker ps -a -q)
 #To remove all images from docker
 #
 # docker rmi $(docker images -a -q)
